#if !canImport(ObjectiveC)
import XCTest

extension LibSGRTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LibSGRTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LibSGRTests.__allTests__LibSGRTests),
    ]
}
#endif
